name: Continuous Integration and Deployment

# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # You can specify the Node.js version here

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint # Assumes there is a lint script in your package.json

      - name: Run Tests
        run: npm test # Assumes there is a test script that runs your unit tests

      - name: Build Project
        run: npm run build # Assumes there is a build script in your package.json
